yt-technology() { youtube-viewer -cv UCvA_wgsX6eFAOXI8Rbg_WiQ ;}
yt-education-yathishdhavala() { youtube-viewer -cv UCkqhJhsQqxo1GfrXadGbJzQ ;}
yt-cultural-alux() { youtube-viewer -cv UCNjPtOCvMrKY5eLwr_-7eUg ;}
yt-education-buttonpoetry() { youtube-viewer -cv UC5DH3eN81b0RGJ7Xj3fsjVg ;}
yt-education-coldfusion() { youtube-viewer -cv UC4QZ_LsYcvcq7qOsOhpAX4A ;}
yt-education-computerscience() { youtube-viewer -cv UCGnKyJ7EZJ7vL_PXkOGLUxw ;}
yt-education-lifenoggin() { youtube-viewer -cv UCpJmBQ8iNHXeQ7jQWDyGe3A ;}
yt-education-mentalfloss() { youtube-viewer -cv UCpZ5qUqpW4hW4zdfuBxMSJA ;}
yt-education-motherboard() { youtube-viewer -cv UCQAUWk_yGz7bk1181DrijNw ;}
yt-education-nerdwritter() { youtube-view er -cv UCJkMlOu7faDgqh4PfzbpLdg ;}
yt-education-seekerdaily() { youtube-viewer -cv UCgRvm1yLFoaQKhmaTqXk9SA ;}
yt-education-teded() { youtube-viewer -cv UCsooa4yRKGN_zEE8iknghZA ;}
yt-education-tedxtalks() { youtube-viewer -cv UCsT0YIqwnpJCM-mx7-gSA4Q ;}
yt-education-theschooloflife() { youtube-viewer -cv UC7IcJI8PUf5Z3zKxnZvTBog ;}
yt-education-thevenusproject() { youtube-viewer -cv UCPNMR_iABvyFmc3G9i1r3Lw ;}
yt-education-thomasfrank() { youtube-viewer -uv electrickeye91 ;}
yt-education-wisecrack() { youtube-viewer -cv UC6-ymYjG0SU0jUWnWh9ZzEQ ;}
yt-health-athleanx() { youtube-viewer -cv UCU_W0oE_ock8bWKjALiGs8Q ;}
yt-language-babbel() { youtube-viewer -cv UC1cyg1VSTs0LDarTxDEHMdQ ;}
yt-language-gabrielwyner() { youtube-viewer -cv UCQAUWk_yGz7bk1181DrijNw ;}
yt-language-langfocus() { youtube-viewer -cv UCNhX3WQEkraW3VHPyup8jkQ ;}
yt-language-learnenglishwithgill() { youtube-viewer -cv UCzBGtBze1AIcDmRwD2ZjiAA ;}
yt-language-lingosteve() { youtube-viewer -cv UCez-2shYlHQY3LfILBuDYqQ ;}
yt-language-lucalampariello() { youtube-viewer -cv UCOJ88yDbqOkAZXNuuYpAAAA ;}
yt-language-nativlang() { youtube-viewer -cv UCMk_WSPy3EE16aK5HLzCJzw ;}
yt-language-polyglotconference() { youtube-viewer -cv UC7P8GqydQqYS_3oE78zqIrg ;}
yt-language-vladimirskultety() { youtube-viewer -cv UCa35MSdCh9gY28WZbBFLnNw ;}
yt-linux-gotbletu() { youtube-viewer -cv UCkf4VIqu3Acnfzuk3kRIFwA ;}
yt-media-complexnews() { youtube-viewer -cv UCpFHkjOa7ia6bH5_6cDsDXg ;}
yt-media-insurgency-broadcast-network() { youtube-viewer -cv UC31hBRkhD2rR0Ehb-3khTfw ;}
yt-media-thealexjoneschannel() { youtube-viewer -cv UCvsye7V9psc-APX6wV1twLg ;}
yt-media-therebelmedia() { youtube-viewer -cv UCGy6uV7yqGWDeUWTZzT3ZEg ;}
yt-media-vice() { youtube-viewer -cv UCn8zNIfYAQNdrFRrr8oibKw ;}
yt-media-wired() { youtube-viewer -cv UCftwRNsjfRo08xYE31tkiyw ;}
yt-philosophy-wirelessphilosophy() { youtube-viewer -cv UCpvhlSLzg2LT89FNUuN-Sig ;}
yt-psychology-actualized() { youtube-viewer -cv UCgeicB5AuF3MyyUto0-M5Lw ;}
yt-psychology-charismaoncommand() { youtube-viewer -cv UCU_W0oE_ock8bWKjALiGs8Q ;}
yt-psychology-mindmastery() { youtube-viewer -cv UCUa1yddTiDkumqduE_FmWzg ;}
yt-science-cosmologytoday() { youtube-viewer -cv UCsPD-BOscDbbf4-djmt-D6A ;}
yt-science-dnewsplus() { youtube-viewer -cv UCe3tPdpxTF7wdBG8uV4hbew ;}
yt-science-dnews() { youtube-viewer -cv UCzWQYUVCpZqtN93H8RR44Qw ;}
yt-science-kurzgesagt() { youtube-viewer -cv UCsXVk37bltHxD1rDPwtNM8Q ;}
yt-science-nakedscience() { youtube-viewer -cv UC8JT2m0mKEgvEtie3JNKwew ;}
yt-science-practicalpsychology() { youtube-viewer -cv UCir93b_ftqInEaDpsWYbo_g ;}
yt-science-psychology() { youtube-viewer -cv UCir93b_ftqInEaDpsWYbo_g ;}
yt-science-sciencenet() { youtube-viewer -cv UCLbyMUSR3-V6D3tXU4i4uug ;}
yt-science-spiritscience() { youtube-viewer -cv UCEcMWs6GudljuLw0-Umf97A ;}
yt-science-veritasium() { youtube-viewer -cv UCHnyfMqiRRG1u-2MsSQLbXA ;}
yt-science-vsauce() { youtube-viewer -cv UC6nSFpj9HTCZ5t-N3Rm3-HA ;}
yt-science-worldsciencefestival() { youtube-viewer -cv UCShHFwKyhcDo3g7hr4f1R8A ;}
yt-stuff-cosmicskeptic() { youtube-viewer -cv UC7kIy8fZavEni8Gzl8NLjOQ ;}
yt-stuff-thoughty2() { youtube-viewer -cv UCRlICXvO4XR4HMeEB9JjDlA ;}
yt-technology-cbtnuggets() { youtube-viewer -cv UClIFqsmxnwVNNlsvjH1D1Aw ;}
yt-technology-davexiang-techchannel() { youtube-viewer -cv UCu44AnfqsP-sRxmZHdnhblw ;}
yt-technology-elithecomputerguy() { youtube-viewer -cv UCJRhK2b92UpOr4LBCWVaFDw ;}
yt-technology-engineeredtruth() { youtube-viewer -cv UChj0w0duKtp7SDd_X9CNptw ;}
yt-technology-linuxdistrocommunity() { youtube-viewer -cv UCq2QwnKW79w4a55ZQqOBReg ;}
yt-technology-simpleprogrammer() { youtube-viewer -cv UCFxdcuY-S6yjZGq_2cjilHg ;}
yt-technology-techsource() { youtube-viewer -cv UChIZGfcnjHI0DG4nweWEduw ;}
yt-technology-cleverprogrammer() { youtube-viewer -cv UCqrILQNl5Ed9Dz6CGMyvMTQ ;}
yt-conspiracy-oddreality() { youtube-viewer -cv UCuftdXePz6z73Wsg8Ao5lTg ;}
yt-technology-joecollings() { youtube-viewer -uv BadEditPro ;}
yt-technology-level1linux() { youtube-viewer -cv UCOWcZ6Wicl-1N34H0zZe38w ;}
yt-technology-crittv() { youtube-viewer -uv razethew0rld ;}
yt-educatuin-theinfographicshow() { youtube-viewer -cv UCfdNM3NAhaBOXCafH7krzrA ;}
